### ISSUE TITLE
Playback problems

### ISSUE THREAD

**Issue by largebugbear** [alyti/jellyvr#20]
I'm trying to play Jellyfin videos via HereSphere and found your proxy, great project :)

Connecting from HereSphere worked fine and I can see videos listed in the web api view.
But regardless of the video container and codec, as soon as I try to start playing anything it fails with the normal popup you get when missing codecs:

```
Failed to open file: "<name>"

Please install the Media Foundation codecs listed on this page:
[...]
```

Even though the needed codecs are definitely installed (playing the same files locally in HereSphere works).
FYI, I tried x264, x265 in MKV and MP4 (all had AAC audio).

I looked at the JSON response sent by jellyvr compared to the HereSphere API doc and it seemed ok, so I'm not sure what the problem might be...

(Let me know if you would like me to post a sample JSON output)

Interestingly, it *does* seem to work, when switching to `DirectShow` as backend instead of `Media Foundation`. Have you observed something like this before?

**Comment by alyti** [comment]
I've only used jellyvr with my Quest 3 and it's version of HereSphere, I can't really comment on what PCVR experience or issues it might have.

**Comment by largebugbear** [comment]
Ah thanks, just took a look into the mentioned channel and saw that apparently someone else ran into the same problem only days ago :D

![image](https://github.com/alyti/jellyvr/assets/166638035/2398ace6-be93-4229-93cd-2dbc33cb32d9)

So it seems like serving the `.m3u8` from Jellyfin (which results in the type `application/vnd.apple.mpegurl`) does not work on PC when using `Media Foundation` in general.

Unless there is a way to get a Jellyfin stream in a different format I guess there is nothing jellyvr could do to get HereSphere to work with this setup.

> PCVR experience or issues it might have

Btw, after switching to `DirectShow` it works flawlessly, so maybe this "first setup pitfall" for PC would be worth putting into the limitations section of the README?
